### ISSUE TITLE
Unable to resolve module `expo-file-system`

### ISSUE THREAD

**Issue by varshan09** [reggie3/react-native-webview-leaflet#70]
Unable to resolve module `expo-file-system` from `node_modules/expo-asset-utils/src/copyAssetToSameDirectoryWithNewNameAsync.js`:
expo-file-system could not be found within the project.

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules: rm -rf node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
    at ModuleResolver.resolveDependency (/Users/varshan/Project/LeafletTest/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:186:15)
    at ResolutionRequest.resolveDependency (/Users/varshan/Project/LeafletTest/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (/Users/varshan/Project/LeafletTest/node_modules/metro/src/node-haste/DependencyGraph.js:282:16)
    at Object.resolve (/Users/varshan/Project/LeafletTest/node_modules/metro/src/lib/transformHelpers.js:267:42)
    at /Users/varshan/Project/LeafletTest/node_modules/metro/src/DeltaBundler/traverseDependencies.js:426:31
    at Array.map (<anonymous>)

**I am getting this error, after importing `WebViewLeaflet` in JS component.**

`import WebViewLeaflet from "react-native-webview-leaflet";`

**Comment by reggie3** [comment]
You need to install the missing module.

**Comment by akiladevinda** [comment]
@reggie3  what need to install ? I also getting this error. My app is not build with expo. What can I do ?
